### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by nickpelton** [boxybird/wordpress-inertia-plugin#1]
Just wanted to say this is awesome. Came across this looking for a way to integrate WP and Inhertia after playing with it on a Laravel setup. I'm very excited about this approach in concept. Looks like it's been a bit stalled since May, curious if you have future plans?

**Comment by boxybird** [comment]
@nickpelton Thank you for the love! 

That's a very good question. "Stalled" is always tough to determine. 

While this plugin was originally inspired by the official Inertia Laravel adapter, it quickly deviated from some of those adapters' features. After all, Laravel and WordPress are completely different tools.

But to answer your question, not much has changed in WordPress since May that would affect the usage of this plugin, so I've tried to avoid tinkering for the sake of tinkering. More importantly, it's been working great for my use cases.

Also, most of the heavy lifting is done in the Inertia JS library, which is updated often. This adapter is fairly lightweight and is built to satisfy the Inertia protocol: https://inertiajs.com/the-protocol.
 
That said, are you seeing issues? Maybe a missing feature?

**Comment by nickpelton** [comment]
I am going to investigate integrating this with my React setup at some point in the future. Was mostly curious if you found the adventure worth the effort AND if you are still using it. Sounds like you are! Thanks Again!
