### ISSUE TITLE
External Redirect Support

### ISSUE THREAD

**Issue by zngly-vlad** [boxybird/wordpress-inertia-plugin#25]
The [official documentation](https://inertiajs.com/redirects) provides a method for returning a location redirect which is not implemented here.

This is very useful when handling redirects to error pages.

```php
return Inertia::location($url);
```

**Comment by boxybird** [comment]
I do like this feature. Unfortunately, WordPress is not a proper MVC framework and this plugin will never have the same feature set as the Laravel version.

Specifically, regarding redirects, this plugin's rendering logic (`Inertia::render`) is executed after the headers have been sent, which is a limitation due to WordPress's template hierarchy. This hierarchy functions more like a 'view' layer rather than a 'controller' layer. Attempting to set redirect headers in a view layer is a bad idea.
